/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppDrawerItem: typeof import('./components/layout/AppDrawerItem.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppNotification: typeof import('./components/layout/AppNotification.vue')['default']
    AppNotificationItem: typeof import('./components/layout/AppNotificationItem.vue')['default']
    AppSettings: typeof import('./components/layout/AppSettings.vue')['default']
    BarChart: typeof import('./components/demo-charts/BarChart.vue')['default']
    CaseList: typeof import('./components/patients/CaseList.vue')['default']
    CaseSetting: typeof import('./components/case/CaseSetting.vue')['default']
    ChartBar: typeof import('./components/demo-charts/ChartBar.vue')['default']
    ChartLine: typeof import('./components/demo-charts/ChartLine.vue')['default']
    ChartPie: typeof import('./components/demo-charts/ChartPie.vue')['default']
    ChartRadar: typeof import('./components/demo-charts/ChartRadar.vue')['default']
    CornerstoneViewer: typeof import('./components/ctview/CornerstoneViewer.vue')['default']
    DetectionCanvas: typeof import('./components/detection/DetectionCanvas.vue')['default']
    DicomUploader: typeof import('./components/ctview/DicomUploader.vue')['default']
    GuideJig: typeof import('./components/case/GuideJig.vue')['default']
    LineChart: typeof import('./components/demo-charts/LineChart.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    NavigationDrawer: typeof import('./components/layout/NavigationDrawer.vue')['default']
    NewPatient: typeof import('./components/patients/NewPatient.vue')['default']
    PanoramicViews: typeof import('./components/detection/PanoramicViews.vue')['default']
    PatientInfo: typeof import('./components/case/PatientInfo.vue')['default']
    PatientList: typeof import('./components/patients/PatientList.vue')['default']
    RouterWrapper: typeof import('./components/layout/RouterWrapper.vue')['default']
    StatsCard: typeof import('./components/StatsCard.vue')['default']
    UploadCTFile: typeof import('./components/case/UploadCTFile.vue')['default']
  }
}
