/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/createCase': RouteRecordInfo<'/createCase', '/createCase', Record<never, never>, Record<never, never>>,
    '/detection': RouteRecordInfo<'/detection', '/detection', Record<never, never>, Record<never, never>>,
    '/guide': RouteRecordInfo<'/guide', '/guide', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/patientInfo': RouteRecordInfo<'/patientInfo', '/patientInfo', Record<never, never>, Record<never, never>>,
    '/planning': RouteRecordInfo<'/planning', '/planning', Record<never, never>, Record<never, never>>,
    '/simulation': RouteRecordInfo<'/simulation', '/simulation', Record<never, never>, Record<never, never>>,
  }
}
